yx - Created Create Announcements Page and changed page header to show the…
ucsb-cs156-f24/proj-happycows-f24-12 pull request #28
Opened 2024-11-21 02:00 UTC by yixuan-wong

## Overview
Created "Create Announcements Page" and updated page header at ```/admin/announcements/{commonsId}/create``` to show the name of the commons.

## Screenshots 
<img width="1241" alt="image" src="https://github.com/user-attachments/assets/22d3350d-4c3b-49cf-87e5-5b1475a827d6">

## Tests
- [x] Frontend Unit tests (`npm test`) pass
- [x] Frontend Test coverage (`npm run coverage`) 100%
- [x] Frontend Mutation tests (`npx stryker run`) 100% 
- [x] Frontend Linting (`npx eslint --fix src`) 

## Dokku Dev Link
https://happycows-dev-yixuan-wong.dokku-12.cs.ucsb.edu

## Validation 
1. Log in with valid account 
2. Under "Admin" in the top bar click on "List Commons"
3. Scroll to the far right column on the table 
4. Click on "Announcements"
5. Click on "Create Announcements"

## Linked Issues
Closes #24

2024-11-22 04:33 UTC, yungongWang approved these changes
LGTM! I log in the website with the validation step, everything looks great! The Announcement page works well.

2024-11-24 05:51 UTC, yungongWang submitted a review, later dismissed
LGTM! I followed the validation step, and everything works really great. The announcement is successfully created.

2024-11-24 22:28 UTC, pconrad requested changes
Can we replace this unwieldy free form text field that requires entering dates in ISO format (which is not ideal), with this nice compact representation from the Create Commons Form?

<img width="636" alt="image" src="https://github.com/user-attachments/assets/1f47d69d-efa7-41ed-a74f-0b4313a7c062">

2024-11-25 04:22 UTC, yungongWang approved these changes
LGTM! The date is transformed to nicer format, and the frontend is fixed

2024-11-25 07:10 UTC, pconrad commented on frontend/src/main/components/Announcement/AnnouncementForm.js
> +    // Stryker restore all
A stryker exception here is a bad idea.  This is the most important code to test!

Let's remove the stryker exception and write the necessary tests.

2024-11-25 07:12 UTC, pconrad commented on frontend/src/main/components/Announcement/AnnouncementForm.js
> +    });
```suggestion
    });
    // Stryker restore all
```

You can't just turn off Stryker whenever you feel like it.  There are only very narrow cases where we are permitted Stryker exceptions, and even some of those should actually be removed from the code base as we know *do* know how to test those.  The number of Stryker exceptions needs to be going *down* not *up*.

2024-11-25 07:13 UTC, pconrad commented on frontend/src/main/components/Announcement/AnnouncementForm.js
> +    // Stryker restore all
You absolutely should be testing this code.

2024-11-25 07:14 UTC, pconrad requested changes
Please remove the stryker exceptions noted and leave only the one around the useForm call. That's the only one that's approved.

For the rest of the code, you need to write the tests.

2024-11-25 07:14 UTC, pconrad commented on frontend/src/main/components/Announcement/AnnouncementForm.js
> +    // Stryker disable all
```suggestion

```

2024-11-25 07:14 UTC, pconrad commented on frontend/src/main/components/Announcement/AnnouncementForm.js
> +    // Stryker restore all
```suggestion

```

2024-11-25 09:25 UTC, closed without merging