Mr-OurTable testing - Reduced runtime still with 100% line, branch, and mutation coverage.
ucsb-cs156-f24/proj-happycows-f24-12 pull request #50
Opened 2024-11-25 19:21 UTC by mayarosenbaum

## Overview

In this PR, I rewrote the OurTable.test.js code to more efficiently test the ourTable.js and produce 100% mutation,line,and branch coverage. I sped up the testing by about 9 minutes.

## Screenshots (Optional)

Below is the original mutation testing runtime:
<img width="649" alt="OriginalMutationTime" src="https://github.com/user-attachments/assets/be856764-5e0e-4ee6-a3b2-cf69658d1d20">
Below is the new mutation testing runtime, still with 100%.
[
<img width="743" alt="NewMutationTime" src="https://github.com/user-attachments/assets/48a9c769-6b77-4f61-b148-50454b1eaa59">
](url)
Below is the new code's 100% branch/line coverage.
<img width="263" alt="Coverage" src="https://github.com/user-attachments/assets/5d0c6479-fb80-4270-9c8f-07a3eb67afc4">

## Feedback Request (Optional)

Please give suggestions on the following:
- I stuck with 100 rows for most of the testing. I'm not sure this is necessary, what do you think?

## Future Possibilities (Optional)

Some possible points could be:
- This is important in possibly testing new features for OurTable. The previous test suite ran really slowly so hopefully this will make testing more efficient.

## Validation (Optional)

1. Download this branch.
2. Run mutation testing for OurTable.js to see runtime/accuracy.
3. Run coverage testing for OurTable.js to see branch/line coverage.

## Tests

- [ ] Backend Unit tests (`mvn test`) pass
- [ ] Backend Test coverage (`mvn test jacoco:report`) 100%
- [ ] Backend Mutation tests (`mvn test pitest:mutationCoverage`) 100% 
- [ ] Frontend Unit tests (`npm test`) pass
- [ ] Frontend Test coverage (`npm run coverage`) 100%
- [ ] Frontend Mutation tests (`npx stryker run`) 100% 
- [ ] Frontend Linting (`npx eslint --fix src`) 

## Linked Issues

Closes #13

2024-11-26 06:19 UTC, yixuan-wong approved these changes, later dismissed
LGTM! I ran and tested locally and I achieved the same results.
<img width="564" alt="image" src="https://github.com/user-attachments/assets/9a0e1f00-8742-4a7b-9911-53c17e3bc9a5">
<img width="572" alt="image" src="https://github.com/user-attachments/assets/a85eb7d7-237b-4952-81ee-bed259cf8c5a">

2024-11-26 08:26 UTC, yixuan-wong approved these changes
Still LGTM!

2024-11-26 23:40 UTC, pconrad requested changes
Please remove package-lock.json and package.json from this PR, since package.json is not changing

2024-11-26 23:55 UTC, pconrad requested changes

2024-11-26 23:55 UTC, pconrad commented on frontend/package.json
>        "lcov"
please remove package.json and package-lock.json from the PR

2024-11-27 00:00 UTC, pconrad commented
replaced by #71

2024-11-27 00:00 UTC, closed without merging